-- V1 schema: cas cliniques, questions, choix et réponses utilisateurs
create table if not exists clinical_cases (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  title text not null,
  specialty text not null default 'Réanimation',
  difficulty text not null default 'Avancé',
  description text,
  created_at timestamptz not null default now()
);
create table if not exists questions (
  id bigint generated by default as identity primary key,
  case_id bigint not null references clinical_cases(id) on delete cascade,
  position integer not null,
  type text not null check (type in ('QCM','QROC')),
  time_limit_seconds integer not null check (time_limit_seconds between 20 and 60),
  stem text not null,
  explanation text,
  expected_keywords text[] default '{}'
);
create table if not exists question_options (
  id bigint generated by default as identity primary key,
  question_id bigint not null references questions(id) on delete cascade,
  position integer not null,
  label text not null,
  is_correct boolean not null default false
);
create table if not exists attempts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  case_id bigint not null references clinical_cases(id) on delete cascade,
  score integer not null,
  total integer not null,
  duration_seconds integer,
  created_at timestamptz not null default now()
);

alter table clinical_cases enable row level security;
alter table questions enable row level security;
alter table question_options enable row level security;
alter table attempts enable row level security;

create policy "public can read cases" on clinical_cases for select using (true);
create policy "public can read questions" on questions for select using (true);
create policy "public can read options" on question_options for select using (true);
create policy "users read own attempts" on attempts for select using (auth.uid() = user_id);
create policy "users insert own attempts" on attempts for insert with check (auth.uid() = user_id);
